version: "3.8"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: manga_tracker
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  web:
    build: ./backend
    depends_on:
      - db
    restart: always
    environment:
      DATABASE_URL: "dbname=manga_tracker user=postgres password=postgres host=db port=5433"
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app

volumes:
  pgdata: